GET http://localhost:27017/todos

###

POST http://localhost:27017/todos/new 
Content-Type: application/json 

{
    "text": "finish project!"
}

###

DELETE http://localhost:27017/todo/DELETE

###
PUT http://localhost:27017/complete/